spring.application.name=backend

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/loja_roupas?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:123456}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=America/Sao_Paulo

spring.jackson.time-zone=America/Sao_Paulo
server.error.include-message=always
server.error.include-binding-errors=never

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:samuelsouzz4@gmail.com}
spring.mail.password=${MAIL_PASSWORD:nfrx apwf foss uyfw}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

app.email.remetente=${MAIL_FROM:samuelsouzz4@gmail.com}
app.email.nome-remetente=${MAIL_FROM_NAME:Garibas Store - Ajuda}
